version: '3.7'

networks:
  smartranking:
    name: network_smartranking

services:
  smartranking-api:
    container_name: smartranking-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    restart: unless-stopped
    command: npm run start:dev
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - smartranking
    ports:
      - 3030:${APP_PORT}

  smartranking-mongo:
    image: mongo
    container_name: smartranking-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    ports:
      - '27030:27017'
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - smartranking

  smartranking-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8030:8081
    depends_on:
      - smartranking-mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: smartranking-mongo
    networks:
      - smartranking
