version: '3.7'

networks:
  smartranking:
    name: network_smartranking

services:
  smartranking-api:
    container_name: smartranking-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    restart: unless-stopped
    command: npm run start:dev
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - smartranking
    ports:
      - 3030:${APP_PORT}